"""owner_names

Revision ID: 801e5f249168
Revises: 94986ed55668
Create Date: 2017-05-25 14:03:03.842360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801e5f249168'
down_revision = '94986ed55668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('owner_firstname', sa.String(length=64), nullable=True))
    op.add_column('record', sa.Column('owner_middlename', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'owner_middlename')
    op.drop_column('record', 'owner_firstname')
    # ### end Alembic commands ###
