"""cases

Revision ID: 9f95c4759220
Revises: 801e5f249168
Create Date: 2017-05-26 12:08:20.277531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f95c4759220'
down_revision = '801e5f249168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund', sa.String(length=8), nullable=True),
    sa.Column('register', sa.Integer(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.String(length=8), nullable=True),
    sa.Column('book_num', sa.Integer(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    op.drop_table('register')
    # ### end Alembic commands ###
