"""Add counter

Revision ID: fa30bc942f7c
Revises: 845befa0f971
Create Date: 2020-06-04 21:40:11.578499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa30bc942f7c'
down_revision = '845befa0f971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_addr', sa.String(length=16), nullable=True),
    sa.Column('first_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_remote_addr'), 'counter', ['remote_addr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counter_remote_addr'), table_name='counter')
    op.drop_table('counter')
    # ### end Alembic commands ###
